const USER_ROLES = Object.freeze({
  SUPER_ADMIN: "SUPER_ADMIN",
  SCHOOL_ADMIN: "SCHOOL_ADMIN"
});

const EMPLOYMENT_STATUS = Object.freeze({
  ACTIVE: "ACTIVE",
  ON_LEAVE: "ON_LEAVE",
  RESIGNED: "RESIGNED",
  INACTIVE: "INACTIVE"
});

const SESSION_STATUS = Object.freeze({
  UPCOMING: "UPCOMING",
  CURRENT: "CURRENT",
  ARCHIVED: "ARCHIVED"
});

const TIMETABLE_STATUS = Object.freeze({
  DRAFT: "DRAFT",
  ACTIVE: "ACTIVE",
  ARCHIVED: "ARCHIVED"
});

const WEEK_PATTERN = Object.freeze({
  EVERY: "EVERY",
  ODD: "ODD",
  EVEN: "EVEN"
});

const TEACHER_CATEGORY = Object.freeze({
  REGULAR: "REGULAR",
  ACTIVITY: "ACTIVITY",
  SPORTS: "SPORTS"
});

const ASSIGNMENT_TYPE = Object.freeze({
  CLASS: "CLASS",
  MEETING: "MEETING",
  ACTIVITY: "ACTIVITY"
});

const ACTIVITY_ASSIGNMENT_TYPES = Object.freeze(["ACTIVITY"]);

const DAYS_OF_WEEK = Object.freeze([
  "SUNDAY",
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
  "SATURDAY"
]);

const TIMETABLE_GRID_DAYS = Object.freeze([
  "MONDAY",
  "TUESDAY",
  "WEDNESDAY",
  "THURSDAY",
  "FRIDAY",
  "SATURDAY"
]);

const DEFAULT_PERIOD_COUNT = 8;
const MAX_PERIOD_COUNT = 16;

const DAILY_TEACHER_STATUS = Object.freeze({
  PRESENT: "PRESENT",
  ABSENT: "ABSENT",
  ON_DUTY: "ON_DUTY",
  FIRST_HALF_OFF: "FIRST_HALF_OFF",
  SECOND_HALF_OFF: "SECOND_HALF_OFF"
});

const SUBSTITUTION_SOURCE = Object.freeze({
  GENERATED: "GENERATED",
  MANUAL: "MANUAL",
  SWAP: "SWAP"
});

const SUBSTITUTION_STATUS = Object.freeze({
  ASSIGNED: "ASSIGNED",
  UNASSIGNED: "UNASSIGNED",
  OVERRIDDEN: "OVERRIDDEN",
  CANCELLED: "CANCELLED"
});

const SUBSTITUTION_RUN_STATUS = Object.freeze({
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
  FAILED: "FAILED"
});

const SUBSCRIPTION_STATUS = Object.freeze({
  NONE: "NONE",
  PENDING: "PENDING",
  TRIALING: "TRIALING",
  ACTIVE: "ACTIVE",
  PAST_DUE: "PAST_DUE",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
  CANCELED: "CANCELED",
  INCOMPLETE: "INCOMPLETE"
});

const BILLING_INTERVAL = Object.freeze({
  MONTHLY: "MONTHLY",
  YEARLY: "YEARLY"
});

const PAYMENT_STATUS = Object.freeze({
  PENDING: "PENDING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  CANCELLED: "CANCELLED",
  REFUNDED: "REFUNDED"
});

const ENQUIRY_STATUS = Object.freeze({
  NEW: "NEW",
  CONTACTED: "CONTACTED",
  REVIEWED: "REVIEWED",
  CLOSED: "CLOSED"
});

const AUDIT_ACTIONS = Object.freeze({
  TEACHER_ADDED: "TEACHER_ADDED",
  TEACHER_EDITED: "TEACHER_EDITED",
  TEACHER_DEACTIVATED: "TEACHER_DEACTIVATED",
  TEACHER_RESIGNED: "TEACHER_RESIGNED",
  DAILY_STATUS_CHANGED: "DAILY_STATUS_CHANGED",
  SUBSTITUTION_GENERATED: "SUBSTITUTION_GENERATED",
  SUBSTITUTION_OVERRIDDEN: "SUBSTITUTION_OVERRIDDEN",
  TIMETABLE_CHANGED: "TIMETABLE_CHANGED",
  SUBSCRIPTION_CHANGED: "SUBSCRIPTION_CHANGED",
  PAYMENT_EVENT: "PAYMENT_EVENT",
  SCHOOL_CREATED: "SCHOOL_CREATED",
  SCHOOL_UPDATED: "SCHOOL_UPDATED",
  USER_CREATED: "USER_CREATED",
  SESSION_CREATED: "SESSION_CREATED",
  SESSION_SET_CURRENT: "SESSION_SET_CURRENT",
  AUTH_LOGIN: "AUTH_LOGIN",
  AUTH_EMAIL_CHANGED: "AUTH_EMAIL_CHANGED",
  AUTH_PASSWORD_CHANGED: "AUTH_PASSWORD_CHANGED",
  ENQUIRY_RECEIVED: "ENQUIRY_RECEIVED",
  CATALOG_ACTIVATED: "CATALOG_ACTIVATED",
  CATALOG_DEACTIVATED: "CATALOG_DEACTIVATED",
  CATALOG_DELETED: "CATALOG_DELETED",
  TEACHER_ACTIVATED: "TEACHER_ACTIVATED",
  TEACHER_DELETED: "TEACHER_DELETED",
  TIMETABLE_SWAP: "TIMETABLE_SWAP",
  TIMETABLE_DELETED: "TIMETABLE_DELETED",
  REVIEW_CREATED: "REVIEW_CREATED",
  REVIEW_UPDATED: "REVIEW_UPDATED",
  REVIEW_DELETED: "REVIEW_DELETED",
  AUDIT_CLEARED: "AUDIT_CLEARED"
});

const ENGINE_VERSION = "1";

module.exports = {
  USER_ROLES,
  EMPLOYMENT_STATUS,
  SESSION_STATUS,
  TIMETABLE_STATUS,
  WEEK_PATTERN,
  TEACHER_CATEGORY,
  ASSIGNMENT_TYPE,
  ACTIVITY_ASSIGNMENT_TYPES,
  DAYS_OF_WEEK,
  TIMETABLE_GRID_DAYS,
  DEFAULT_PERIOD_COUNT,
  MAX_PERIOD_COUNT,
  DAILY_TEACHER_STATUS,
  SUBSTITUTION_SOURCE,
  SUBSTITUTION_STATUS,
  SUBSTITUTION_RUN_STATUS,
  SUBSCRIPTION_STATUS,
  BILLING_INTERVAL,
  PAYMENT_STATUS,
  AUDIT_ACTIONS,
  ENQUIRY_STATUS,
  ENGINE_VERSION
};
